name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: sudo apt install libsqlite3-mod-spatialite
      - run: pipenv sync --dev
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: make install_plugins
      - run: make
      - run: make deploy